version: '3'
services:
  kreed:
    image: daiveed/kreed:latest
    networks:
      - kreed
    restart: always
    env_file:
      - .env
    ports:
      - '3000:3000'
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis

  database:
    image: postgres:alpine
    networks:
      - kreed
    environment:
      DATABASE_URL: postgresql://kreed-backend_owner:npg_XXX@ep-little-leaf-a1bhgzms-pooler.ap-southeast-1.aws.neon.tech/kreed-backend?sslmode=require

  redis:
    image: redis:alpine
    networks:
      - kreed
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
  caddy:
    image: caddy:latest
    container_name: caddy
    networks:
      - kreed
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - my-app
    restart: unless-stopped

networks:
  kreed:
    driver: bridge

volumes:
  redis-data:
  caddy_data:
  caddy_config:
