name: Deploy CI

on:
  push:
    branches:
      - main

jobs:
    Build-and-push-image:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout repository
          uses: actions/checkout@v4

        - name: Create .env file      
          run: |
              echo "PORT=3000" >> ".env"
              echo -e "PORT=3000\nDATABASE_URL=${{ secrets.DATABASE_URL }}" > .env
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ".env"
              echo "CLIENT_APP_URL=${{ secrets.CLIENT_APP_URL }}" >> ".env"
              echo "GOOGLE_API_BASE_URL=${{ secrets.GOOGLE_API_BASE_URL }}" >> ".env"
              echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> ".env"
              echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> ".env"
              echo "IAM_USERNAME=${{ secrets.IAM_USERNAME }}" >> ".env"
              echo "SMTP_ENDPOINT=${{ secrets.SMTP_ENDPOINT }}" >> ".env"
              echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> ".env"
              echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> ".env"
              echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> ".env"
              echo "FIREBASE_PRIVATE_KEY=${{ secrets.FIREBASE_PRIVATE_KEY }}" >> ".env"
              echo "FIREBASE_CLIENT_EMAIL=${{ secrets.FIREBASE_CLIENT_EMAIL }}" >> ".env"
              echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> ".env"
              echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ".env"
              echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ".env"
              echo "AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }}" >> ".env"
          #
        #
        # - name: Log in to the Container registry
        #   uses: docker/login-action@v3
        #   with:
        #     registry: registry.digitalocean.com
        #     username: kreed-container
        #     password: ${{ secrets.DGO_SECRET_TOKEN }}
        #
        # - name: Build and push Docker image
        #   uses: docker/build-push-action@v6
        #   with:
        #     context: .
        #     push: true
        #     tags: |
        #       registry.digitalocean.com/kreed-container/kreed:latest
        #       registry.digitalocean.com/kreed-container/kreed:${{ github.sha }}


    deploy:
      runs-on: ubuntu-latest
      needs:
        - Build-and-push-image
      steps:
        - name: Build container image
          run: docker compose up -d

        - name: Log in to DigitalOcean Container Registry with short-lived credentials
          run: doctl registry login --expiry-seconds 1200

        - name: Push image to DigitalOcean Container Registry
          run: docker push registry.digitalocean.com/kreed-container/kreed:$(echo $GITHUB_SHA | head -c7)
